<?php


namespace App\Helpers\Table\HTML2\Builder\Elements;

class Header extends Main
{

    public function build()
    {
        return parent::build(); // TODO: Change the autogenerated stub
    }

    public function attribute(string $atr)
    {
        return parent::attribute($atr); // TODO: Change the autogenerated stub
    }

    public function child($bool = false)
    {
        return parent::child($bool); // TODO: Change the autogenerated stub
    }

    public function innerText(string $text)
    {
        return parent::innerText($text); // TODO: Change the autogenerated stub
    }

    public function element($class = null, $innerText = "", $child = false)
    {
        return parent::element($class, $innerText, $child); // TODO: Change the autogenerated stub
    }
}